name: Ejecutar Python para Teradata y Descargar Excel

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Comprobar código fuente
      uses: actions/checkout@v2
    
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usa la versión de Python que prefieras

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias desde el archivo requirements.txt

    - name: Ejecutar script Python
      run: |
        python funciones.py  # Reemplaza 'tu_script.py' con el nombre de tu script

    - name: Subir Excel generado
      uses: actions/upload-artifact@v2  # Cambié la versión a v2
      with:
        name: excel-file
        path: ./reporte_teradata.xlsx  # Ajusta esto si el archivo tiene otro nombre o está en otro directorio


