name: Ejecutar Python para Teradata y Descargar Excel

on:
  push:
    branches: [main]

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Comprobar código fuente
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
 
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
 
    - name: Configurar VPN con OpenConnect
      run: |
        sudo apt-get update
        sudo apt-get install -y openconnect
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect ${{ "SURA-VPN" }} --user=${{ secrets.VPN_USER }} --passwd-on-stdin --no-cert-check &
      
    - name: Esperar a que la VPN se conecte
      run: |
        sleep 10  # Espera 10 segundos para asegurarte de que la VPN esté conectada

    - name: Configurar DNS para la VPN
      run: |
        echo "nameserver 10.99.47.1" | sudo tee /etc/resolv.conf  # Reemplazar con el DNS correcto de tu VPN

    - name: Verificar configuración DNS
      run: |
        cat /etc/resolv.conf  # Verificar si el DNS se ha configurado correctamente

    - name: Verificar resolución de teraifx
      run: |
        nslookup teradata2.suranet.com  # Verifica si teraifx se resuelve correctamente

    - name: Verificar conectividad con teraifx
      run: |
        ping -c 4 teradata2.suranet.com  # Verifica la conectividad con teraifx a través de la VPN

    - name: Ejecutar script Python
      run: |
        python main.py
 
    - name: Subir Excel generado
      uses: actions/upload-artifact@v4
      with:
        name: my-data
        path: ./reporte_teradata.xlsx
