name: Ejecutar Python para Teradata y Descargar Excel

on:
  push:
    branches: [main]

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Comprobar código fuente
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Usa la versión de Python que prefieras

    - name: Ejecutar script Python
      run: |
        python main.py  # Reemplaza 'tu_script.py' con el nombre de tu script

    - name: Subir Excel generado
      uses: actions/upload-artifact@v2  # Cambié la versión a v2
      with:
        name: excel-file
        path: ./reporte_teradata.xlsx  # Ajusta esto si el archivo tiene otro nombre o está en otro directorio


